### PR TITLE
ITM-478/ITM-521: Integrate with updated SoarTech DryRun server

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
- Migrate KDMAs to include SoarTech kde's and update SoarTech alignment targets
- Update API version to 0.3.2 for DRE (this touches 100-plus files)
- SoarTech only returns session alignment if all probes are answered.

See [server PR](https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/96).

To test, run the latest ADEPT and SoarTech servers and run the various session types against them.
If you haven't already, you'll have to copy the latest TA1 scenarios to your configured location.  I'll send them to you under separate cover.

I would change ITMSession's `self.ta1_integration` to True, then run the various TA1 session types:
- `python itm_minimal_runner.py --name foobar --session adept`
- `python itm_minimal_runner.py --name foobar --session adept --training`
- `python itm_minimal_runner.py --name foobar --session soartech`
- `python itm_minimal_runner.py --name foobar --session soartech --training`

You'll see server errors (especially for SoarTech scenarios) and SoarTech scenarios only return session alignment when the scenario/alignment target match (e.g., qol scenario with a qol alignment target).  All of the ADEPT ones should return session alignment.

### CODE REVIEW

**Review by brianpippin — APPROVED** [review]

**Comment by dereknop** [comment]
> All of the ADEPT ones should return session alignment.

Screenshot 2024-07-25 at 9 44 54 AM

When I run `python3 itm_minimal_runner.py --name foobar --session adept` I get `nan` for the alignment. 
I am on the dre branch for ST server and main for Adept. I also ran `./gradlew` to ensure my models were current. 
Then I tried to run `python3 itm_minimal_runner.py --name foobar --session eval` and got the following:
Screenshot 2024-07-25 at 9 43 48 AM

**Comment by nextcen-dgemoets** [comment]
> Any ideas on what I am doing wrong?

You're not doing anything wrong, but I haven't addressed the `eval` session type yet, just `soartech` and `adept`.  That said, the error you encountered is with saving JSON output, which can be enabled manually and should probably work now.  I'll develop a fix.  Thank you!

In the meantime, you can try `soartech` and `adept` sessions, with and without `--training`.

**Review by phile-caci — APPROVED** [review]
Everything looks good on my end.

**Review by Ayal-Ciobotaru — APPROVED** [review]
lgtm!

**Pull request merged**
