### PR TITLE
ITM-114: Update Human ADM Sim

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
Update the Human ADM Sim (`itm_human_scenario_runner.py`) to the action-based API used in the September '23 milestone.

- Removed all probes and probe responses
- Added getting available actions and taking the actions available in the action space
- Prompt for action-specific parameters as necessary.

Note that the list of treatment locations is NOT based on where the casualties' injuries are-- it is always a fixed, complete list of possible locations.

### CODE REVIEW

**Review by kdrumm — APPROVED** [review]
Seems to work for me.  

One non-blocking suggestion is to alter the __repr__ function in some classes that get printed so they actually print pretty.  I know the Action class benefited from this.  Just make sure it doesn't break anything else.

```
 def __repr__(self):
        """For `print` and `pprint`"""
        return json.dumps(self.to_dict(), indent=4)
```

**Comment by nextcen-dgemoets** [comment]
> Seems to work for me.
> 
> One non-blocking suggestion is to alter the **repr** function in some classes that get printed so they actually print pretty. I know the Action class benefited from this. Just make sure it doesn't break anything else.
> 
> ```
>  def __repr__(self):
>         """For `print` and `pprint`"""
>         return json.dumps(self.to_dict(), indent=4)
> ```

Hmm, the `Action` class is generated by Swagger so I'm not sure I want to add our own mods to it because we'll have to re-apply it every time.  That said, it is a useful thing.  Maybe doc in the README as a development/testing tip?

Or were there some non-model classes you thought we might add this to?

**Comment by kdrumm** [comment]
> > Seems to work for me.
> > One non-blocking suggestion is to alter the **repr** function in some classes that get printed so they actually print pretty. I know the Action class benefited from this. Just make sure it doesn't break anything else.
> > ```
> >  def __repr__(self):
> >         """For `print` and `pprint`"""
> >         return json.dumps(self.to_dict(), indent=4)
> > ```
> 
> Hmm, the `Action` class is generated by Swagger so I'm not sure I want to add our own mods to it because we'll have to re-apply it every time. That said, it is a useful thing. Maybe doc in the README as a development/testing tip?
> 
> Or were there some non-model classes you thought we might add this to?

Good call!  I'm sure we could work something out such that we can add it to the print call at `itm_human_scenario_runner.py:281`.  That would also isolate it to just the human runner.  I tried that at first, but response isn't always an object.  I can take a look at it tomorrow morning.

**Review by brianpippin — APPROVED** [review]
I didn't see any issues.

**Comment by nextcen-dgemoets** [comment]
From @kdrumm : 

> I spent [more time] trying to find a good way to pretty print all the output.   Short of writing a manual recursive json writer, I don't have any good ideas

**Pull request merged**
