### PR TITLE
ITM-510

### PR DESCRIPTION
**Pull request by Ayal-Ciobotaru**
Added 'justification' as a requirement for `action` and added `medical_policies` controlled vocab

### CODE REVIEW

**Comment by Ayal-Ciobotaru** [comment]
Adjusting based on discussion with Darren

**Review by nextcen-dgemoets — CHANGES_REQUESTED** [review]
Need to update all clients so that they return justifications.  Ideally, human client will let you hit return to send a canned justification, or let you specify your own.

**Comment by nextcen-dgemoets** [comment]
There's one more client that needs an update-- the `itm_adm_scenario_runner.py`, in the same location as the other two clients.

**Comment by Ayal-Ciobotaru** [comment]
Sorry, I'm still not super familiar with all the clients. Added the justification to `itm_adm_scenario_runner.py`

**Review by nextcen-dgemoets — APPROVED** [review]

**Review by dereknop — APPROVED** [review]

**Pull request merged**
