### PR TITLE
Add injury location and expand get_scenario error code 400

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
Parallel PR for [server side](https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/27), which had most of the changes.  Regenerated model from YAML and updated injury locations in client.

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
This looks like we have a list of locations duplicated throughout the code.  I didn't verify item by item, but is there a need to duplicate them instead of listing it once in a single place?

**Comment by nextcen-dgemoets** [comment]
> This looks like we have a list of locations duplicated throughout the code. I didn't verify item by item, but is there a need to duplicate them instead of listing it once in a single place?

It's defined in the `Injury` object in the model, but the valid values for the enum aren't available from the generated class.  I believe there's a way in Swagger to create an object type whose whole purpose is to serve as the enum of valid values, but I haven't looked into that.  Either way, ideally this would be generated from the swagger and all users (clients and server) would get the list of valid values from the generated class.

**Comment by kdrumm** [comment]
> It's defined in the `Injury` object in the model, but the valid values for the enum aren't available from the generated class. I believe there's a way in Swagger to create an object type whose whole purpose is to serve as the enum of valid values, but I haven't looked into that. Either way, ideally this would be generated from the swagger and all users (clients and server) would get the list of valid values from the generated class.

I looks like we could use this: [https://swagger.io/docs/specification/data-models/enums/](https://swagger.io/docs/specification/data-models/enums/).  Go to the `Reusable enums` section.  I can look into that if you're interested.

**Comment by nextcen-dgemoets** [comment]
> I looks like we could use this: https://swagger.io/docs/specification/data-models/enums/. Go to the `Reusable enums` section. I can look into that if you're interested.

That would be great!  🥇  Or you could write a new ticket for it and look into it for all similar cases (triage categories, injury types, supply types, etc.).  But if you just want to address it for locations as part of this PR, that's fine too and we can subsequently migrate the other enums.

**Review by kdrumm — APPROVED** [review]
I have another PR where the team can debate a potential fix for code duplication.

**Review by brianpippin — APPROVED** [review]

**Comment by nextcen-dgemoets** [comment]
> I have another PR where the team can debate a potential fix for code duplication.

After discussion, I'll merge this PR as-is then will review @kdrumm 's PR for ITM-124.

**Pull request merged**
