### PR TITLE
ITM-604: Have client not choose APPLY_TREATMENT if insufficient supplies

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
Before, we when an `APPLY_TREATMENT` action was randomly chosen (whether pre-configured as an action mapping by the scenario or just as a non-restricted action), if the clients needed to provide a treatment (that is, if it wasn't preconfigured by the scenario), it would only choose from among the available supplies.

Now, it will also:
- handle if there are no available supplies (by choosing another action)
- handle if pre-configured actions specify an unavailable pre-configured supply (by choosing another action)
- handle if there are no other available actions other than one which requires an unavailable supply (by gracefully exiting with a meaningful error message).

**NOTE**: The human input sim will only allow choosing another supply, not another action.  Also, I finally removed the "mock" ADM client that isn't used and has been wholly replaced by the itm minimal runner.

To test, run each of the three clients with 
- e.g., `python itm_minimal_runner.py --name itm604 --session adept --scenario DryRunEval-MJ4-eval`
- e.g., `python itm_human_input.py --session adept --scenario DryRunEval-MJ4-eval`

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
> @nextcen-dgemoets , was there an updated `itm\__init__.py`?

Yep, forgot to commit it-- thanks.

**Review by phile-caci — COMMENTED** [review]
1. Sometime in human input (python itm_human_input.py --session adept --scenario DryRunEval-MJ4-eval), when I take an action, I get this:
```
Traceback (most recent call last):
  File "C:\Dev\ITM\itm-evaluation-client\itm\itm_human_scenario_runner.py", line 330, in perform_operations
    response = self.take_action_operation()
  File "C:\Dev\ITM\itm-evaluation-client\itm\itm_human_scenario_runner.py", line 261, in take_action_operation
    return self.take_or_intend_action(intend_action=False)
  File "C:\Dev\ITM\itm-evaluation-client\itm\itm_human_scenario_runner.py", line 305, in take_or_intend_action
    return self.itm.take_action(session_id=self.session_id, body=action) if not intend_action else self.itm.intend_action(session_id=self.session_id, body=action)
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\api\itm_ta2_eval_api.py", line 784, in take_action
    (data) = self.take_action_with_http_info(session_id, **kwargs)  # noqa: E501
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\api\itm_ta2_eval_api.py", line 851, in take_action_with_http_info
    return self.api_client.call_api(
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\api_client.py", line 148, in __call_api
    response_data = self.request(
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\api_client.py", line 358, in request
    return self.rest_client.POST(url,
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\rest.py", line 263, in POST
    return self.request("POST", url,
  File "C:\Dev\ITM\itm-evaluation-client\swagger_client\rest.py", line 222, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (400)
Reason: BAD REQUEST
HTTP response headers: HTTPHeaderDict({'Server': 'Werkzeug/2.2.3 Python/3.10.11', 'Date': 'Tue, 01 Oct 2024 17:55:51 GMT', 'Content-Type': 'application/json', 'Content-Length': '40', 'Connection': 'close'})      
HTTP response body: b'"Cannot intend actions via take_action"\n'
```

2. Also, in human input, when I used blood, the inventory went down as expected, but when I used a tourniquet, the inventory didn't go down, even though reusable is false.
`{'quantity': 1, 'reusable': False, 'type': 'Tourniquet'}`

3. Had the client run through these in the background:
Didn't see any more errors when running out of supplies.
```
python itm_minimal_runner.py --name foobar --session eval  
python itm_minimal_runner.py --name foobar --session adept  
python itm_minimal_runner.py --name foobar --session adept --training  
python itm_minimal_runner.py --name foobar --session soartech  
python itm_minimal_runner.py --name foobar --session soartech --training  
python itm_minimal_runner.py --name foobar --session test --scenario conditional_mappings   
python itm_minimal_runner.py --name foobar --session adept --train --scenario DryRunEval.IO1 
python itm_minimal_runner.py --name foobar --session soartech --train --scenario qol-dre-1-train 
```
Ran in huma

**Comment by nextcen-dgemoets** [comment]
> 1. Sometime in human input (python itm_human_input.py --session adept --scenario DryRunEval-MJ4-eval), when I take an action, I get this:
> 
> ```
> Traceback (most recent call last):
> swagger_client.rest.ApiException: (400)
> Reason: BAD REQUEST
> [deletia]
> HTTP response body: b'"Cannot intend actions via take_action"\n'
> ```

This is because when the ADM (or human in this case) expresses an **intent** to take an action, it needs to use the `intend_action` API call instead of `take_action`.  It's annoying in the human client, because you have to look for `intent: True` in the action mappings so you can know which action type (intend or take) to choose.

> 2. Also, in human input, when I used blood, the inventory went down as expected, but when I used a tourniquet, the inventory didn't go down, even though reusable is false.
>    `{'quantity': 1, 'reusable': False, 'type': 'Tourniquet'}`

What injury was it treating?  A treatment will only consume a tourniquet if it's used successfully, e.g. for an amputation or certain punctures.  If you see this happening for such an injury, LMK for sure.

**Comment by phile-caci** [comment]
Ah.. thanks @nextcen-dgemoets , that was exactly it.

**Review by phile-caci — APPROVED** [review]
LGTM!

**Comment by dereknop** [comment]
Running with dev server. 

python3 itm_minimal_runner.py --name foobar --session eval  

causes this :

 line 222, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (500)
Reason: INTERNAL SERVER ERROR
HTTP response headers: HTTPHeaderDict({'Server': 'Werkzeug/2.2.3 Python/3.11.4', 'Date': 'Fri, 04 Oct 2024 14:04:47 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '251', 'Connection': 'close'})
HTTP response body: b'{\n  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",\n  "status": 500,\n  "title": "Internal Server Error",\n  "type": "about:blank"\n}\n'

I assume there is something wrong with my setup on my end. I _believe_ my config.ini file is correct after including all of the updates to the template. Is it problematic if I am pointing to the prod endpoints (ADEPT_URL=https://darpaitm.caci.com/adept) instead of having them stood up locally?

**Comment by nextcen-dgemoets** [comment]
@dereknop  What is the error/traceback in the server logging?

**Review by dereknop — APPROVED** [review]
My path to my scenario files was incorrect... looks good now

**Pull request merged**
